name: Build and Release APK

on:
  push:
    branches:
      - main  # Triggers on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step to create google-services.json from secret
      - name: Create google-services.json
        run: |
          echo "${{ secrets.FIREBASE_CONFIG }}" > $GITHUB_WORKSPACE/app/google-services.json

      # Step to debug google-services.json content (Masked Output)
      - name: Debug google-services.json content
        run: |
          cat $GITHUB_WORKSPACE/app/google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        continue-on-error: true  # Continue workflow even if this step fails

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Release APK
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          release_name: Release on Main Branch
          assets: |
            app/build/outputs/apk/release/app-release.apk
