name: Build and Release Unsigned APK

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create google-services.json
        run: |
          echo '${{ secrets.FIREBASE_CONFIG }}' > $GITHUB_WORKSPACE/app/google-services.json
          echo "google-services.json content for debug:"
          cat $GITHUB_WORKSPACE/app/google-services.json

      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace
        env:
          JAVA_HOME: ${{ runner.tool_cache }}/Java_Zulu_jdk/17.0.13-11/x64

      - name: Get Version Code
        id: get_version_code
        run: |
          # Extract versionCode from build.gradle
          VERSION_CODE=$(grep versionCode app/build.gradle | awk '{print $2}')
          echo "VERSION_CODE: $VERSION_CODE"
          echo "{ \"version_code\": \"$VERSION_CODE\" }" > version.json

      - name: Check APK file exists
        id: check_apk
        run: |
          if [ -f app/build/outputs/apk/release/app-release-unsigned.apk ]; then
            echo "Unsigned APK file found at expected location."
            echo "::set-output name=apk_url::https://github.com/${{ github.repository }}/releases/latest/download/app-release-unsigned.apk"
          elif [ -f app/build/outputs/apk/release/app-release.apk ]; then
            echo "Signed APK file found."
            echo "::set-output name=apk_url::https://github.com/${{ github.repository }}/releases/latest/download/app-release.apk"
          else
            echo "APK file not found. Checking other possible locations..."
            find app/build/outputs -name "*.apk"
            echo "::set-output name=apk_url::APK_NOT_FOUND"
          fi

      - name: Release APK and Version File
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest  # Use the same tag as before
          name: Release on Main Branch
          artifacts: |
            app/build/outputs/apk/release/app-release-unsigned.apk
            version.json  # Include the version file in the release
          makeLatest: true
          updateOnlyUnreleased: false  # Allow updates to any existing release
          allowUpdates: true  # Allow updates to the release
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.13-11/x64

      - name: Commit Version Code
        if: github.event.head_commit.message != 'Update version.json with version code'
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add version.json
          git commit -m "Update version.json with version code ${{ steps.get_version_code.outputs.version_code }}"
          git push

      - name: Output APK and Version File URLs
        run: |
          echo "APK URL: ${{ steps.check_apk.outputs.apk_url }}"
          echo "Version JSON URL: https://github.com/${{ github.repository }}/releases/latest/download/version.json"
