name: Build and Release APK

on:
  push:
    branches:
      - main  # Triggers on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # Updated to the latest version
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step to create google-services.json from secret
      - name: Create google-services.json
        run: |
          echo "${{ secrets.FIREBASE_CONFIG }}" > $GITHUB_WORKSPACE/app/google-services.json

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Release APK
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Default GitHub Token
          tag: latest
          name: Release on Main Branch
          artifacts: app/build/outputs/apk/release/app-release.apk
          generateReleaseNotes: false
          makeLatest: legacy  # Keeps the release versioning consistent
          omitBody: false
          skipIfReleaseExists: false
