name: Build and Release APK

on:
  push:
    branches:
      - main  # Triggers when pushing to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'  # Ensuring compatibility with Firebase Crashlytics

      # Step 3: Cache Gradle dependencies to speed up build
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Build the APK using Gradle
      - name: Build APK
        run: ./gradlew assembleRelease

      # Step 5: Upload the APK as a release asset
      - name: Release APK
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest  # This will create a release with the 'latest' tag, ensuring updates without a versioned tag
          release_name: Release on Main Branch
          assets: |
            app/build/outputs/apk/release/app-release.apk

      # Step 6: Echo the download link
      - name: Output Download Link
        run: |
          echo "APK download link: https://github.com/${{ github.repository }}/releases/download/latest/app-release.apk"
